---
# handlers file for add_nginx_proxy_conf

- name: Enable vhost
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ domain }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ domain }}.conf"
    owner: www-data
    group: www-data
    state: link
  notify: Restart nginx

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
