---
dependency:
  enabled: no
driver:
  name: docker
platforms:
  - name: buster
    image: library/debian:buster
lint: |
  set -e
  yamllint .
  ansible-lint --exclude roles/ --exclude molecule/ --exclude library/
  flake8 --exclude roles,molecule,library
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
scenario:
  name: default
verifier:
  name: testinfra
